#!/bin/bash

# TODOS:
# 1) add more error handling
# 2) make functions reference local vars, not $1 etc. 
# 3) add function to swap records
# 4) add functionality to list all logs.
# make pretty!

new_log() {
  DATA_DIR="$HOME/.local/share/bashlog/${1}_bashlog.csv"
  mkdir -p "$(dirname "${DATA_DIR}")"

  if [[ -f "${DATA_DIR}" ]]; then
    echo "Error, log with that name already exists at: ${DATA_DIR}"
    exit 1
  fi

  touch "${DATA_DIR}" || {
    echo "Error, could not create log at ${DATA_DIR}"
    exit 1
  }

  echo "Log made successfully at ${DATA_DIR}"
}

read_log() {
  DATA_DIR="$HOME/.local/share/bashlog/${1}_bashlog.csv"

  if [[ ! -f "${DATA_DIR}" ]]; then
    echo "Error, there is no log with that name: ${DATA_DIR}"
    exit 1
  fi

  width=$(tput cols)
  length=$((${#1} + 2))
  number=$(( ($RANDOM % 7) + 1 ))
  border=$(printf =%"${length}"s= | tr " " "=")
  tput setaf ${number}
  tput hpa $(((width / 2) - (length / 2)))
  echo "${border}"
  tput hpa $(((width / 2) - (length / 2)))
  echo "= ${1} = "
  tput hpa $(((width / 2) - (length / 2)))
  echo "${border}"
  tput setaf 9

  nl -s ') ' "${DATA_DIR}" | while read -r line; do
    tput hpa $(((width / 2) - (length / 2)))
    tput setaf ${number}
    echo -n "| "
    tput setaf 9
    echo "${line}"
  done
}

update_log() {
  DATA_DIR="$HOME/.local/share/bashlog/${1}_bashlog.csv"

  if [[ ! -f "${DATA_DIR}" ]]; then
    echo "Error, there is no log with that name: ${DATA_DIR}"
    exit 1
  fi

  sed -i -e '$a\' "${DATA_DIR}"
  
  first_line=$(head -n 1 "${DATA_DIR}")
  echo "Completing ${first_line}"
  read -p "Continue? (y/n) " confirm

  if [[ "${confirm}" == "y" ]]; then
    sed -i '1d' "${DATA_DIR}"
    echo "Completed!" 
  else
    echo "Cancelled"
  fi 
}

delete_log() {
  DATA_DIR="$HOME/.local/share/bashlog/${1}_bashlog.csv"

  if [[ ! -f "${DATA_DIR}" ]]; then
    echo "Error, there is no log with that name: ${DATA_DIR}"
    exit 1
  else
    rm "${DATA_DIR}"
    echo "Log has been successfully deleted."
  fi

}

add_to_log() {
    LOG="${1}"
    DATA_DIR="$HOME/.local/share/bashlog/${LOG}_bashlog.csv"
    NEW_ENTRY="${2}" 

    if [[ ! -f "${DATA_DIR}" ]]; then
      echo "Error, there is no log with that name: ${DATA_DIR}"
      exit 1
    fi 

    if [[ -s "${DATA_DIR}" ]] && [[ $(tail -c1 "${DATA_DIR}" | wc -l) -eq 0 ]]; then
        echo >> "${DATA_DIR}"
    fi
    
    echo "${NEW_ENTRY}" >> "${DATA_DIR}" 

    echo "${NEW_ENTRY} has been added to log ${LOG}"

}

main() {
  while getopts "n:r:u:a:d:h" flag; do
    case $flag in
      n)
        log="${OPTARG}"
        new_log "${log}"
        # TODO: Should return and evaluate a code here. google standard
        ;;
      r)
        log_to_read="${OPTARG}"
        read_log "${log_to_read}"
        ;;
      u)
        log_to_update="${OPTARG}"
        update_log "${log_to_update}"
        read_log "${log_to_update}"

        ;;
      a)
        log_to_add="${OPTARG}"
        log_to_update="${!OPTIND}"
        # maybe shift here to remove positional arg. 
        add_to_log "${log_to_add}" "${log_to_update}"
        read_log "${log_to_add}"
        ;;
      d)
        log_to_delete="${OPTARG}"
        delete_log "${log_to_delete}"
        ;;
      h)
        echo "Usage: ${0} [-n Maker a new log] [-r Read a log] [-u Log to update] [-a (Log to add to) (New item)] [-d Delete a log] [-l List all logs] [-h]"
        ;;
      ?)
        echo "Invalid option: -${OPTARG}"
        exit 1
        ;;
    esac
  done 
}

main "$@" 
      
      
    

    